updating to windows 0.58
vsrs/windows_safe_handle pull request #1
Opened 2024-07-12 20:53 UTC by psandana

- Updating dependency to consume `windows@0.58.0`
- Adapting code to new API
- Adapting test to new API
- Bumping version `v0.2.0`

2024-07-12 20:55 UTC, psandana commented
Hi @vsrs. I found this project, and it is very interesting. I need something like this for `windows` crate version `0.58.0`. Would you like my contribution to upgrade this package to be compatible with it?

If you accept the changes, it would be required that a new version is released. I already did changes to update the version to `v0.2.0`.

Thanks,
Pato!

2024-07-17 09:22 UTC, vsrs requested changes
@psandana, thank you for your contribution :)

LGTM! I have only minor suggestions.

Also, it might be worth mentioning in the README that v1 can be used for older windows crate versions.

2024-07-17 09:22 UTC, vsrs commented on tests/bcrypt_hash.rs
>          Ok(handle)
```rust
result.to_hresult().map(|| handle)
```

2024-07-17 09:22 UTC, vsrs commented on tests/bcrypt_hash.rs
>          Ok(handle)
```
result.to_hresult().map(|| handle)
```

2024-07-17 09:22 UTC, vsrs commented on tests/bcrypt_hash.rs
> +        Ok(length)
```
result.to_hresult().map(|| length)
```

2024-07-17 18:24 UTC, merged

2024-07-17 18:37 UTC, vsrs commented
@psandana,
I've published the new version. Thank you once again.